# Generated by Django 4.2.1 on 2023-05-24 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя мастера')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Услуга')),
                ('duration', models.IntegerField(default=30, verbose_name='Продолжительность услуги (мин.)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Saloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название салона')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес салона')),
                ('master', models.ManyToManyField(blank=True, related_name='saloons', to='site_reception.master', verbose_name='Мастера в салоне')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Когда создана запись')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='client', to='site_reception.client', verbose_name='Клиент')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='master', to='site_reception.master', verbose_name='Выбранный мастер')),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='saloon', to='site_reception.saloon', verbose_name='Выбранный салон')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='service', to='site_reception.service', verbose_name='Выбранная услуга')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='services', to='site_reception.service', verbose_name='Услуги предоставляемые мастером'),
        ),
    ]
