# Generated by Django 4.2.1 on 2023-05-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='service',
            field=models.ManyToManyField(related_name='services', to='site_reception.service', verbose_name='Услуги предоставляемые мастером'),
        ),
    ]
