# Generated by Django 4.2.1 on 2023-05-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_reception', '0002_alter_master_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appointment_date',
            field=models.DateField(null=True, verbose_name='Дата записи'),
        ),
        migrations.AddField(
            model_name='order',
            name='appointment_status',
            field=models.CharField(choices=[('booked', 'Забронирован'), ('payed', 'Оплачен'), ('done', 'Выполнен/Отменен')], default='booked', max_length=20, verbose_name='Статус записи'),
        ),
        migrations.AddField(
            model_name='order',
            name='appointment_time',
            field=models.CharField(choices=[('10-00', 'Утро 10-00'), ('10-30', 'Утро 10-30'), ('11-00', 'Утро 10-30'), ('11-30', 'Утро 10-30'), ('12-00', 'День 12-00'), ('12-30', 'День 12-30'), ('13-00', 'День 13-00'), ('13-30', 'День 13-30'), ('14-00', 'День 14-00'), ('14-30', 'День 14-30'), ('15-00', 'День 15-00'), ('15-30', 'День 15-30'), ('16-00', 'День 16-00'), ('16-30', 'День 16-30'), ('17-00', 'Вечер 17-00'), ('17-30', 'Вечер 17-30'), ('18-00', 'Вечер 18-00'), ('18-30', 'Вечер 18-30'), ('19-00', 'Вечер 19-00'), ('19-30', 'Вечер 19-30'), ('20-00', 'Вечер 20-00'), ('20-30', 'Вечер 20-30'), ('21-00', 'Вечер 21-00'), ('21-30', 'Вечер 21-30')], max_length=20, null=True, verbose_name='Время записи'),
        ),
    ]
