# Generated by Django 4.2.1 on 2023-05-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_reception', '0003_order_appointment_date_order_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='master_images/', verbose_name='Фото мастера'),
        ),
        migrations.AddField(
            model_name='saloon',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='saloon_images/', verbose_name='Фото салона'),
        ),
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/', verbose_name='Изображение для услуги'),
        ),
    ]
