# Generated by Django 4.2.1 on 2023-05-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_reception', '0004_master_photo_saloon_photo_service_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='master_images/', verbose_name='Фото мастера'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='saloon_images/', verbose_name='Фото салона'),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='service_images/', verbose_name='Изображение для услуги'),
        ),
    ]
