# Generated by Django 4.2.1 on 2023-05-25 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_reception', '0005_alter_master_photo_alter_saloon_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('star', models.IntegerField(default=1, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Когда написан отзыв')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='author', to='site_reception.client', verbose_name='Автор отзыва')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='review_master', to='site_reception.master', verbose_name='Мастер')),
            ],
        ),
    ]
