# Generated by Django 4.2.1 on 2023-05-29 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_reception', '0008_alter_order_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='client', to='site_reception.client', verbose_name='Клиент'),
        ),
    ]
